#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=AlexNet --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=ResNet18 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=Xception --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=AlexNet --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=ResNet34 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/

#python train_imageNet.py --epochs=50 --batch_size=32 --model_name=ResNet18 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=50 --batch_size=64 --model_name=ResNet18 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=50 --batch_size=128 --model_name=ResNet18 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=100 --batch_size=128 --model_name=ResNet18 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#
#
#python train_imageNet.py --epochs=50 --batch_size=32 --model_name=ResNet34 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=50 --batch_size=64 --model_name=ResNet34 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=50 --batch_size=128 --model_name=ResNet34 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/
#python train_imageNet.py --epochs=100 --batch_size=128 --model_name=ResNet34 --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/


#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=ImageNet --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/

python train_imageNet.py --epochs=2 --batch_size=32 --model_name=ResNet18 --lr=0.001 --image_resolution=320 --resize_value=500 --adjust_lr_flag=False --model_save_path=../checkpoint/model_norm.pth --log_file_name=../result/model_training/log_norm.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/

#python train_imageNet.py --epochs=30 --batch_size=32 --model_name=AlexNet --lr=0.001 --image_resolution=224 --resize_value=300 --adjust_lr_flag=False --model_save_path=../checkpoint/model.pth --log_file_name=../result/model_training/log.txt --train_data_path=../data/image_split/train/ --test_data_path=../data/image_split/test/ --val_data_path=../data/image_split/val/