# ----------> content shift + slack <-------------
##.........default: e=0.1, iter=10, w_1=w_2=w_3=0.33
## 0.5%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=512 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 1%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=1024 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 2%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=2048 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 4%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=4096 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 8%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=8192 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 16%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=16384 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 32%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=32768 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
## 64%
python adv_attack_against_3detectors.py --adversary=PGD --eps=0.1 --alpha=0.7 --iter_steps=10 --partial_dos=False --content_shift=True --slack=True --combine_w_slack=False --log_file_for_result=../result/same_input_format_3detectors/pgd_0.1_10/result_file.txt --preferable_extension_amount=0 --preferable_shift_amount=65536 --test_data_path=../data/all_file/ --test_label_path=../data/test_mal_label.csv --model_path_1=../checkpoint/malconv_model.pth --model_path_2=../checkpoint/fireeye_model.pth --model_path_3=../checkpoint/AvastNet_model.pth --use_cpu=1 --batch_size=1 --first_n_byte=102400 --window_size=500
